### PR TITLE
chore: update plugin for Intellij 2023.3

### PR DESCRIPTION
**Pull request by niels-s**
We were updating the plugin to be able to run with Intellij 2023.3 versions. We had to include a few system upgrades to facilitate bumping the maximum build version.

1. Upgrade the Gradle version to 8.5 to overcome the error:
```
Unsupported class file major version 63
```

2. Upgrade the Gradle Kotlin and IntelliJ plugins to fix the error:
```
The binary version of its metadata is 1.9.0, and the expected version is 1.7.1.
```

I've followed the instructions in
https://intellij-support.jetbrains.com/hc/en-us/community/posts/15634389368722-After-updating-to-intellij-2023-3-my-plugin-is-incompatible-and-does-not-build-anymore and https://stackoverflow.com/a/75180866/1132127 to solve the problem.

### CODE REVIEW

**Comment by niels-s** [comment]
Ah I missed there was already #70. @zzehring I'll leave it up to you to decide what PR to pick and merge

**Comment by haocheng** [comment]
@niels-s 
Thank you for the PR for supporting 2023.3 👍 

I have tried to build the plugin manually and installed it. However, I would see errors like this after installing the updated plugin

```
com.intellij.diagnostic.PluginException: Cannot create extension (class=org.wso2.lsp4intellij.listeners.LSPTypedHandler) [Plugin: com.github.zzehring.intellijjsonnet]
at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1471)
at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:71)
at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:32)
at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:468)
at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:416)
at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:249)
at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.kt:44)
at com.intellij.codeInsight.editorActions.TypedHandlerPreloader$execute$2.invokeSuspend(TypedHandlerPreloader.kt:19)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ClassNotFoundException: org.wso2.lsp4intellij.listeners.LSPTypedHandler PluginClassLoader(plugin=PluginDescriptor(name=Jsonnet Language Server, id=com.github.zzehring.intellijjsonnet, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2023.3/plugins/instrumented-intellij-jsonnet-0.1.6.jar, version=0.1.6, package=null, isBundled=false), packagePrefix=null, state=active)
at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:2255)
at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:1370)
at com.intellij.openapi.extensions.impl.InterfaceExtensionImplementationClassResolver.resolveImplementationClass(InterfaceExtensionImplementationClassResolver.kt:19)
at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:50)
```

Just curious if you have met the same issue? 🤔

**Comment by zzehring** [comment]
Sorry for the delay as I've been on holiday. Thanks for the PR! So, I've merged https://github.com/zzehring/intellij-jsonnet/pull/70 instead of this one (for now) just due to fewer moving pieces (and it still passed build). I'll cherrypick from here if need be.

**Comment by zzehring** [comment]
Gonna close this one out as #70 seems to be stable.

**Pull request closed without merging**
